[2021-04-13 17:36:40,250] [INFO] [base._start_message] -> 
                 --------------------------------------------------
                 Starting fuzzing session
                 Target: TcpTarget
                 UI: EmptyInterface
                 Log: ./kittylogs/kitty_20210413-173639.log

                 Total possible mutation count: 2
                 --------------------------------------------------
                                 Happy hacking
                 --------------------------------------------------
            
[2021-04-13 17:36:40,255] [INFO] [ics_fuzzer.start] -> Skipping environment test
[2021-04-13 17:36:40,275] [INFO] [ics_fuzzer._start] -> should keep running? True
[2021-04-13 17:36:40,723] [INFO] [tcp.pre_test] -> host>>>>10.150.203.90
[2021-04-13 17:36:40,723] [INFO] [tcp.pre_test] -> port>>>>102
[2021-04-13 17:36:42,852] [ERROR] [tcp.pre_test] -> Error: Traceback (most recent call last):
  File "/home/uzio/APPs/Fuzz-master/katnip/targets/tcp.py", line 61, in pre_test
    sock.connect((self.host, self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
timeout: timed out

[2021-04-13 17:36:42,853] [ERROR] [tcp.pre_test] -> Failed to connect to target server, retrying...
